### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by povilasb** [ropez/pytest-describe#10]
Does `pytest-describe` support contexts?

From README:
```
def describe_my_function():
    def with_default_arguments():
    def with_some_other_arguments():
    def it_throws_exception():
    def it_handles_exception():
```

The way I'm trying to use this is:
```
def describe_ensure_bits_count():
    def with_bits_count_more_than_number_bit_count():
        def it_returns_unaltered_specified_number():
            assert_that(ensure_bits_count(10, 16), is_(10))
```
This way, the test case is not discovered.

But when I do it like this:
```
def describe_ensure_bits_count():
    def it_returns_unaltered_specified_number_with_bits_count_more_than_number_bit_count():
        assert_that(ensure_bits_count(10, 16), is_(10))
```
it works like a charm.

Am I trying to use it in a wrong way, or is this functionality just not supported?

**Comment by ropez** [comment]
Yes, you can do that. You just need to prefix the inner function correctly, e.g:

    def describe_ensure_bits_count():
        def describe_with_bits_count_more_than_number_bit_count():
            def it_returns_unaltered_specified_number():
                assert_that(ensure_bits_count(10, 16), is_(10))

If you really want to use just `with_`, you can add this to your pytest.ini:

    describe_prefixes = ('describe', 'with')

**Comment by povilasb** [comment]
Worked like a charm, thank you :)
