### ISSUE TITLE
Shared behaviours

### ISSUE THREAD

**Issue by ghostsquad** [ropez/pytest-describe#12]
I have a use case where I would like to use describe methods inside of a class in order to avoid test duplication by allowing me to use inheritance. Though, using classes is not strictly required. The end goal is to get to something like:

https://www.relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples

proposed syntax without test class inheritance

```
@pytest_describe.shared
def share_a_measurable_object()

   def describe_include():
      def with_an_item_in_the_collection_returns_true(subject):
      def with_an_item_not_in_the_collection_returns_false(subject):

@pytest_describe.behaves_like('a measurable object')
def describe_my_special_array():

   @pytest.fixture
   def subject():
       return MySpecialArray()

@pytest_describe.behaves_like('a measurable object')
def describe_another_array():
   
   @pytest.fixture
   def subject():
         return AnotherArray()

   def it_does_something_special(subject):
```

**Comment by ghostsquad** [comment]
I wish I could do a PR for this, but the pytest plugin architecture is kind of difficult to grok.

**Comment by ropez** [comment]
I think this is a very good idea. I have used this pattern in other frameworks (Jasmine etc). I guess I simple haven't needed it yet in my python projects.

Maybe, if I can find some time, I will see if this can be done

**Comment by ropez** [comment]
@ghostsquad I managed to hacked together something quite easily. See the example in the commit message above. The code is in the behaves_like branch. Would you care to test it?

I didn't follow your example exactly, bacause:
- I generally don't like strings that refer to code. I like to be able to use grep to find all references to a function.
- I didn't find a reason to annotate the behavior function, so there's only one decorator, the `behaves_like`, which takes the function as an argument.

**Comment by ropez** [comment]
This is also a possibility. Kind of in the spirit of pytest's "funcargs":

```
from pytest import fixture
from pytest_describe import behaves_like

@pytest_describe.shared_behavior
def a_duck():
    def it_quacks(sound):
        assert sound == "quack"

def describe_something_that_quacks(a_duck):
    @fixture
    def sound():
        return "quack"

def describe_something_that_barks(a_duck):
    @fixture
    def sound():
        return "bark"
```

**Comment by ghostsquad** [comment]
@ropez you are my hero! I started a PR, kinda stumbling through a similar code path that you implemented. I completely agree about not having strings that refer to code, your suggestion is 100x better than mine. ;)

Not annotating the behavior makes perfect sense. I like that the only requirement is that the "behavior" function just needs to be imported into the test module so it can be referenced. It feels much more natural that way.

I don't really like the `funcargs` in this scenario, because you never reference the `a_duck` argument within the describe block (or tests). In addition, it's not clear what that parameter is even doing. The `@behaves_like(a_duck)` is great though!

I'll pull down that branch and play around with it, and add some more tests.

💯
