### ISSUE TITLE
Nicer test output?

### ISSUE THREAD

**Issue by chrischambers** [ropez/pytest-describe#15]
It'd make for a nicer BDD workflow if we could see gherkin-style red/green colourised reporting with checkmarks. To use the example provided in the docs:
```
$ pytest --spec-output
--------------------------------------------------------------------------------------
- path.to.spec:

List:
  Append:
    ✓ adds to end of list
  Remove:
    ✓ removes items from list
    ✗ fails
```

This would be even nicer with a ```--watch``` flag which observes new/changed files recursively.

**Comment by ropez** [comment]
Won't fix.

Sorry, this is a test collection plugin for **py.test**, not a BDD framework or anything like that. Please direct suggestions about test output to **py.test** directly. There may be other plugins that provide the type of output you want, see http://plugincompat.herokuapp.com/

As for watching for file changes, you can use the **pytest-xdist** plugin, and run with `py.test -f`.

**Comment by chrischambers** [comment]
I've improved pytest-spec so that it understands nested scopes, primarily for this plugin -the pull request is [here](https://github.com/pchomik/pytest-spec/pull/18).

**Comment by ropez** [comment]
Looks neat
