### ISSUE TITLE
consider moving under pytest-dev

### ISSUE THREAD

**Issue by bubenkoff** [ropez/pytest-describe#5]
Please consider moving under pytest-dev
pytest.org/latest/contributing.html#submit-a-plugin-co-develop-pytest

**Comment by ropez** [comment]
I think publishing on github and pypi is as far as I'm going to go with this. I'm not against it, if you want to take the initiative of getting this included in the pytest-dev community. However, I don't think I'm going to bother with mailing lists for the time being. We're using this internally, and it works fine for us.
