### ISSUE TITLE
Are you planning to make this work for python 3?

### ISSUE THREAD

**Issue by kwmiebach** [ropez/pytest-describe#6]

**Comment by ropez** [comment]
Yes, the plan is to make it work for python 3.

In fact, I had no reason to believe that it didn't already work with python 3. The tests are set up to run with 2.7 and 3.4, and are passing.

Is there any problem in particular that you could describe?

**Comment by kwmiebach** [comment]
OK, thank you, I will try with python 3.4 locally

I looked at the travis log:

https://travis-ci.org/ropez/pytest-describe/jobs/57008327

I am not sure what these config lines in https://github.com/ropez/pytest-describe/blob/6d5e0724deda2f0816a112f4126a230d8d799037/.travis.yml mean:

  - TOX_ENV=py34-pytest26
  - TOX_ENV=py34-pytest27

**Comment by ropez** [comment]
They are references to tox.ini

I can see it's a little bit confusing, because travis provides options for running with different versions of python, but here we're using tox for that. From travis' perspective, it's using 2.7 for all the tests.

**Comment by kwmiebach** [comment]
I am using pytest-describe with python 3.4 now for some time without any issues. Turns out to be very useful.
