### ISSUE TITLE
__multicall__ being deprecated in upcoming pytest release

### ISSUE THREAD

**Issue by jacebrowning** [ropez/pytest-describe#8]
When running `pytest` with this plugin, a warning now appears:

```
================================================ pytest-warning summary ================================================
WI1 .../pytest_describe/plugin.py:101 'pytest_pycollect_makeitem' hook uses deprecated __multicall__ argument
```

**Comment by ropez** [comment]
@jacebrowning Can you please try the current master, and see if this works better for you. In particular, check that all your tests are still being collected and run.

**Comment by jacebrowning** [comment]
No more warnings in `master`. Looks :+1: for a new release.
